### PR TITLE
Add F-beta score

### LINKED ISSUE #85: Suggestion for formalizing F beta score
Hi stato peeps,

We are trying to record confidence F scores for markers of cells in our ontology (PCL/BDSO) and was wondering if you had any suggestions on standard ways to annotate that statistic. Below is what we are trying represent: 
Screenshot 2022-02-17 at 13 19 23

Thanks!

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #85 

Hi @proccaserra thought I'd try to edit the ontology. 
I've only edited ODK based GO-style ontologies, so not 100% sure I did everything right here. 
We are also unsure on how to use this (a class) to annotate axioms - was wondering if you had any experience with this. 

also tagging @hkir-dev @dosumis 

Thanks

### CODE REVIEW

**Review by proccaserra — COMMENTED** [review]
@shawntanzk a quick comment as I saw F-beta score is asserted under F-statistic. I figured out this is not ideal as the F-beta score does not follow an F-distribution and would be a subtype.
It'd be better suited as a child of 'score' and we could define it with respect to other types. I'll try something soon. 
thx again!

**Comment by shawntanzk** [comment]
> F-beta score does not follow an F-distribution

Thanks for figuring this out :) honestly would have never known. child of 'score' sounds good! I'm guessing you have some other ideas so I'll leave the fix to you then. Thanks so much once again!

**Comment by proccaserra** [comment]
@shawntanzk  to appear in release 1.5 with the following uri: http://purl.obolibrary.org/obo/STATO_0000663

**Comment by shawntanzk** [comment]
Wow what a throwback :) thanks so much @proccaserra! @dosumis & @hkir-dev - pinging you about this, guess you'd want to swap out the property in BDSO. Thanks all!

**Comment by proccaserra** [comment]
@shawntanzk sorry it took so long

**Comment by shawntanzk** [comment]
@proccaserra no worries at all :) I know these things take time. Throwback comment was more of a positive nostalgic feeling to the good times I had at EBI doing ontology development stuff :)

**Pull request closed without merging**
